Default: &defaults
  user: darth
  password: ""
  host: localhost
  port: 5432
  database: fayde
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: fayde_test
  <<: *defaults

Staging:
  database: fayde_staging
  poolsize: 100
  <<: *defaults

Production:
  database: fayde_production
  poolsize: 100
  <<: *defaults
